appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mcikRB0gDq33OREdkHLWiXkWY0owJg9HtZJV5eLl1VnhNY97hbQa9lpIijKzLTTBGA3aW9iazyGLVkZODcbpDzvB6w/3ycyQQnIbwZmBWyaQV+yIjv8Uj7W92lsr8g+U9rASebyxZuvVxrWueugIcrl1yl2WOLggjEvey3BMOHbg8+YyL+fP+6qaIJjqL2n7SsBRJLVhmyh2EU21druDXF0/jVt7IjlYR3ImpaqAKJ1CbtMduORKFk8Qq2uaHfC6cyrTDgUj9xeUdJgbROge2sLYUoYBeGmB2ZFLtHBsbcWm9iyjukLBDOL425e48Xziq/ljKEgWRRfCm3k42XrlyqIPYLygJIgxB624frUJhGiOOZo05fCrNL7vqDXWg39y4gFUNT95U9MES+rbBDWqMrNtjtUj1BzKj2/pYjLPP4noCqD6HS8A3DtcOBUHL2ynKoAu/5Q+k2ULbBrIOf8xPcLyTbqdlYD880V+0IWdD5lBnKhKUOGS+hhPDQcPc/QN08MSzQ0sQy8HTebG87z4OBOmh7FQSkmJHyRBhpxx1zlfKWVbmuA8LdS/DiGSkwjyvj3IVWU+jB1+HS4GzijKZ8xVFdBlZkcndIm3M7q8BdlBsTYIc/KkR8ZNk1GIunhUFQYev6FfWG60+0881nvo/78mmOkz7F78LzRlRPGPjsY=}
